language: python
python:
  - "3.9"
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install coverage
  - pip install prospector
script:
  - python -m unittest tests.test_calculations
  - coverage run -m unittest tests.test_calculations
  - coverage report -m
  - prospector test_calculations
after_success:
  - coveralls
