language: python
python:
  - "3.9"
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install coverage
  - pip install --upgrade pyflakes
  - pip install selenium
  - pip install flask_testing
  - pip install app
script:
  - python -m unittest tests.test_calculations
  - coverage run -m unittest tests.test_calculations
  - coverage report -m
  - pyflakes src/app.py
  - pyflakes src/bmiFunctions.py
  - pyflakes src/retFunctions.py
  - pyflakes tests/test_calculations.py
  - python -m unittest tests.test_front_end.py
after_success:
  - coveralls
