language: python
python:
  - "3.9"
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install coverage
  - pip install --upgrade pyflakes
script:
  - python -m unittest tests.test_calculations
  - coverage run -m unittest tests.test_calculations
  - coverage report -m
  - pyflakes src/app.py
  - pyflakes src/bmiFunctions.py
  - pyflakes src/retFunctions.py
after_success:
  - coveralls
